apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-server
  template:
    metadata:
      labels:
        app: ai-server
    spec:
      containers:
      - name: ai-server
        image: guhyun9454/microservice_programming:latest
        ports:
        - containerPort: 9454

---
apiVersion: v1
kind: Service
metadata:
  name: ai-server-service
spec:
  selector:
    app: ai-server
  ports:
  - port: 9454
    targetPort: 9454